# Generated by Django 5.1.7 on 2025-03-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('external_lawyer', 'External Lawyer'), ('internal_lawyer', 'Internal Lawyer'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
