# Generated by Django 5.1.7 on 2025-03-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresettoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
