# Generated by Django 5.1.7 on 2025-03-27 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appellant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('is_minor', models.BooleanField(default=False)),
                ('birth_place', models.CharField(blank=True, max_length=100, null=True)),
                ('fical_code', models.CharField(max_length=30)),
                ('dob', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widow', 'Widow'), ('separated', 'Separate/Separate'), ('busy', 'Busy')], max_length=20, null=True)),
                ('drive_folder_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppellantFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='temp_files/')),
                ('drive_file_id', models.CharField(blank=True, max_length=100, null=True)),
                ('drive_file_link', models.URLField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('appellant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='cases.appellant')),
            ],
        ),
    ]
