# Generated by Django 5.1.7 on 2025-03-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appellant',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
