# Generated by Django 5.1.7 on 2025-03-27 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_appellant_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=100, null=True)),
                ('village', models.CharField(blank=True, max_length=100, null=True)),
                ('ad_type', models.CharField(blank=True, choices=[('In The Compilation Phase', 'In The Compilation Phase'), ('In Process', 'In Process'), ('File Sent', 'File Sent'), ('File Approved', 'File Approved'), ('File Filed With The Court', 'File Filed With The Court'), ('Assignment And Role Number', 'Assignment And Role Number'), ('Court', 'Court'), ('Hearing Date', 'Hearing date'), ('Sentence', 'Sentence'), ('Transcript Of Proceedings (Municipality)', 'Transcript Of Proceedings (Municipality)')], max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='appellant',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widow', 'Widow'), ('separated', 'Separate'), ('busy', 'Busy'), ('engaged', 'Engaged'), ('relationship', 'Relationship')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('court_no', models.CharField(max_length=100)),
                ('descendant', models.CharField(blank=True, max_length=100, null=True)),
                ('des_birth_place', models.CharField(blank=True, max_length=100, null=True)),
                ('married_to', models.CharField(blank=True, max_length=100, null=True)),
                ('marriage_date', models.DateField(blank=True, null=True)),
                ('spouse_citizenship', models.CharField(blank=True, max_length=100, null=True)),
                ('grand_parents_dod', models.DateField(blank=True, null=True)),
                ('clause_1', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('In The Compilation Phase', 'In The Compilation Phase'), ('In Process', 'In Process'), ('File Sent', 'File Sent'), ('File Approved', 'File Approved'), ('File Filed With The Court', 'File Filed With The Court'), ('Assignment And Role Number', 'Assignment And Role Number'), ('Court', 'Court'), ('Hearing Date', 'Hearing date'), ('Sentence', 'Sentence'), ('Transcript Of Proceedings (Municipality)', 'Transcript Of Proceedings (Municipality)')], max_length=50, null=True)),
                ('is_consolare', models.BooleanField(default=False)),
                ('is_judicial', models.BooleanField(default=False)),
                ('clause_2', models.CharField(blank=True, max_length=100, null=True)),
                ('clause_3', models.CharField(blank=True, max_length=100, null=True)),
                ('clause_4', models.CharField(blank=True, max_length=100, null=True)),
                ('total_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_place', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_payment', models.DateField(blank=True, null=True)),
                ('appellants', models.ManyToManyField(related_name='cases', to='cases.appellant')),
                ('grand_parents_dop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='death_address', to='cases.address')),
                ('lawyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to=settings.AUTH_USER_MODEL)),
                ('marriage_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marriage_address', to='cases.address')),
                ('generation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_generations', to='cases.generation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
