# Generated by Django 5.1.7 on 2025-03-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_address_generation_alter_appellant_marital_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='ad_type',
            field=models.CharField(blank=True, choices=[('marriage', 'Marriage'), ('death', 'Death')], max_length=50, null=True),
        ),
    ]
