# Generated by Django 5.1.7 on 2025-03-27 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_alter_address_ad_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='generation',
        ),
        migrations.AddField(
            model_name='generation',
            name='case',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='cases.case'),
            preserve_default=False,
        ),
    ]
