# Generated by Django 5.1.7 on 2025-03-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_case_created_by_case_des_birth_dod'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
