# Generated by Django 5.1.7 on 2025-04-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_alter_case_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='court_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('In The Compilation Phase', 'In The Compilation Phase'), ('In Process', 'In Process'), ('File Sent', 'File Sent'), ('File Approved', 'File Approved'), ('File Filed With The Court', 'File Filed With The Court'), ('Assignment And Role Number', 'Assignment And Role Number'), ('Court', 'Court'), ('Hearing Date', 'Hearing date'), ('Sentence', 'Sentence'), ('Transcript Of Proceedings (Municipality)', 'Transcript Of Proceedings (Municipality)')], default='In The Compilation Phase', max_length=50),
        ),
    ]
