# Generated by Django 5.1.7 on 2025-04-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_alter_case_court_no_alter_case_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='clause_1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='clause_2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='clause_3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='clause_4',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
