# Generated by Django 5.1.7 on 2025-05-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_alter_appellant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='payment_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='payment_status',
            field=models.CharField(choices=[('COMPLETED', 'COMPLETED'), ('PENDING', 'PENDING'), ('FAILED', 'FAILED'), ('VOIDED', 'VOIDED')], default='PENDING', max_length=20),
        ),
    ]
